// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type ApiKey struct {
	ID         int64        `json:"id"`
	Name       string       `json:"name"`
	KeyHash    string       `json:"key_hash"`
	Permission string       `json:"permission"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Item struct {
	ID          int64        `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}
