// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountAPIKeys(ctx context.Context) (int64, error)
	CountItems(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	DeleteAPIKey(ctx context.Context, id int64) error
	DeleteItem(ctx context.Context, id int64) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetItem(ctx context.Context, id int64) (Item, error)
	ListAPIKeys(ctx context.Context) ([]ApiKey, error)
	ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
}

var _ Querier = (*Queries)(nil)
